### PR TITLE
Updated courses table to remove location and added session type, enro…

### PR DESCRIPTION
**Pull request by Irving-Delgad0**
…lled students, and difficulty

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Loom Video
https://www.loom.com/share/4c682beb990e461e9035ea5a02548e01

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by AnthonyLayne — APPROVED** [review]
Thank you for adding the missing data to the backend. The code looks good, couldn't find any errors. Great job!

**Review by Rlauckern — APPROVED** [review]
Good clean code and now there's enrolled students. Thanks.

**Review by techlando — APPROVED** [review]
great job! it's clean, readable, and definitely valuable data needed for the application to run smoothly!

**Review by tkordysh — APPROVED** [review]
Thanks for updating the db, code looks good.

**Review by Roadlyfe — APPROVED** [review]
Everything makes sense to me. Great work!

**Review by AlexiusThomas — COMMENTED** [review]
Code looks good, not seeing any obvious mistake

**Pull request merged**
