### PR TITLE
Fix/clear errors from unused imports and issues with get instructor by id function

### PR DESCRIPTION
**Pull request by katherineyevsukov**
## Description

Several unused imports leftover from when the admin router/model files were removed were preventing the server from running. The get instructor classes route was also breaking, due to a model function being called in the check instructor exists middleware not existing. Created that function and cleaned up and updated the route. Server is now running and route is pulling data appropriately

## Loom Video

[Please paste a link here of a quick loom video walking through what you did in your PR .
](https://www.loom.com/share/86f74897df344575b58b39b33a1a4737)
## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by mcmillanj — APPROVED** [review]
great catch on the unused  imports and  parsing

**Review by Cheyenneb96 — APPROVED** [review]
thank you for fixing this

**Review by waylonturbes — APPROVED** [review]
Nice job finding and removing those unneeded imports and that `try` `catch` block surrounding the `then` `catch` block for the GET instructor classes endpoint.

**Review by mark-escosura — APPROVED** [review]
Good job keeping code as DRY as possible. Also kudos to you for taking out imports that aren't being used!

**Pull request merged**
