### PR TITLE
Bl 562 be create middleware for course registration

### PR DESCRIPTION
**Pull request by techlando**
## Description

Create middleware that covers the three cases as pointed out in the attached discovery ticket:

-Check age is between course constraints

-Check if a course exists for addEnrolledCourse and getEnrolledCourses

-Check if a course is full

It was discovered that for addEnrolledCourse and getEnrolledCourses there is a bug. Potential think its's the way data is being relayed from the get params ":id".

Fixes # (issue)
Middleware filters request for acceptably criteria

## Ticket
https://bloomtechlabs.atlassian.net/browse/BL-562

## Loom Video

https://www.loom.com/share/c406956593a3423c82460a512e2f3d88

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Cassius-Cassity — APPROVED** [review]

**Review by Cassius-Cassity — APPROVED** [review]

**Comment by Cassius-Cassity** [comment]
I am sure you already checked this but in code climate, it sites two places where the code may need to be refactored.

**Review by AnthonyLayne — APPROVED** [review]
The code you wrote looks good, I appreciate the comments you added explaining future fixes and current bugs that will have to be worked out. Great Job!

**Review by tkordysh — APPROVED** [review]
Well done guys, the middleware seems to be working well and it surely cleans up the childrenRouter. Maybe the bug with the previous middleware can be scoped out into its own ticket, but it seems like the new one you put it does the trick.

**Review by Irving-Delgad0 — APPROVED** [review]
This is great! middleware is definitely a necessity, good job on the code and writing comments about bugs and such that could potentially be made into tickets

**Review by Roadlyfe — APPROVED** [review]
This looks great! Clean code, easily readable, excellent notes. Awesome work.

**Review by AlexiusThomas — COMMENTED** [review]
Good insight for those-that-come-after.

**Pull request merged**
