### PR TITLE
Feature/parent-router-tests

### PR DESCRIPTION
**Pull request by lizzythomson**
Co-authored by: Eduardo Escobar @EduarddoEscobar 

## Description

- Created tests for all parent router endpoints. 
- Deleted old parent router test file because the tests were testing endpoints that no longer exist

Fixes # (issue)

## Loom Video

https://www.loom.com/share/5ce957d3dacc4783b32a338a07882297

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by sharontsanchez — APPROVED** [review]
Good work on setting up some testing for the parent router! It's great to see the CRUD operations set up for students and schedules.  Simple and Effective Implementation. Great work Lizzy & Eddy!!

**Review by dconley1212 — APPROVED** [review]
All of these tests look great! This awesome!

**Review by bugsbrog — APPROVED** [review]
I like how you cleaned up your code so that the older parentRouter.test file wasn't there just testing endpoints that didn't exist anymore. Also, nice job on the tests! I watched your loom and was very impressed with how you walked through what every test was testing for!

**Comment by paulstgermain** [comment]
Great work here - I wanted to highlight what you said in your Loom recording: "...So that we are only testing the logic in the router"

This is big, because when testing it's really easy to struggle with testing your actual code and logic and not mistakenly testing PostgreSQL or Express itself as I've seen folks do in the past - awesome job highlighting that here!

**Review by peterdavidconley — COMMENTED** [review]
Routers tests look clean and descriptive. Great use of the "toHaveProperty" by keeping the test simple for the 404 error. Same deal with the 200 test.

**Pull request merged**
