### PR TITLE
Bl 825 be subtask add date

### PR DESCRIPTION
**Pull request by Irving-Delgad0**
## Description

This was a quick fix, updated courses and instructors table to aid with rendering of dates and sorting functionality 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Cassius-Cassity — APPROVED** [review]

**Review by reneetro — APPROVED** [review]
Awesome! Simple addition that might add a lot of value to the users so they know when the course was created

**Review by lisamdespain — APPROVED** [review]
This is a great change - I can imagine it will be useful when sorting courses by most recent, in addition to start date. 2 ways this could be presented in the FE: as a sort by most recent or as a field presented to the user, in which case it could be trimmed to just show the date, I would think. Overall, useful functionality added here. Great job!

**Review by vasilii-garanin — APPROVED** [review]
Hi guys, these are good additions. Small but mighty! Want to note that I think you forgot to link your Loom video.

**Comment by gclancy121** [comment]
These changes look good to me!

**Review by Roadlyfe — APPROVED** [review]
clean code! great job.

**Review by mack-gallagher — APPROVED** [review]
These look like clean insertions of table columns to me!

**Comment by theecolya** [comment]
this is good to go

**Review by theecolya — APPROVED** [review]
this is good to go

**Pull request merged**
