### PR TITLE
ownerAuthorization created and implemented

### PR DESCRIPTION
**Pull request by DanielReinagel**
### Don't merge until the roles table has been added and merged
Requires the roles table PR to be merged before this works.

## Description

Some put and delete endpoints now require you to either be the owner or be an admin of a higher role than the owner.

Fixes # (issue)

https://trello.com/c/zCelOwBN/162-a-user-may-update-or-delete-their-own-user-or-classes-or-whatever-the-user-may-own-an-admin-or-superadmin-can-delete-or-update-u

## Loom Video

Video probably coming soon.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by MarkTrepanier — APPROVED** [review]
fantastic! This is going to make things so much more simple. Good explanation. Good amount of commits, but try to make the commit messages present tense

**Comment by CamMeiners** [comment]
This all looks good, I just finished up the Roles table, it hasn't been merged but this should be good to go once that PR is merged.

**Review by CamMeiners — APPROVED** [review]
Everything looks good, I just got the PR for the roles table up so once it's merged this should be good to merge too.

**Review by natecheney-dev — APPROVED** [review]
Good implementation of authorization to ensure correct user flow, looks good once the roles table is working properly

**Pull request merged**
