### PR TITLE
Feature calendar model courses

### PR DESCRIPTION
**Pull request by JakeHappel**
## Description

These are model functions for the calendar we need to be able to add, update, and delete courses from the calendar aka CRUD.

Fixes # (issue)

## Loom Video

https://www.loom.com/share/b935235e1ab34ad79bbfc76f8c934de0

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Ogden-R — APPROVED** [review]
everything looks good to me. it is very important to be able to edit the items on the calendar, so i appreciate that this is being done. great work!

**Review by spencerlonghurst — APPROVED** [review]
Looks great! I enjoy seeing these components doing good productive work for the UI. Good job!

**Review by leewp8 — APPROVED** [review]
The work looks well thought out and organized, but it does seem like some of the auto-checks are failing. You might need to take another look.

**Review by ShahWahidy — APPROVED** [review]
Looks good Jake. your code is well written. I would love to see the rest of your routing and how feed data from BE to your component. good luck

**Review by Michael-Subbarao — APPROVED** [review]
Changes look clean, these will be very useful endpoints.

**Review by joseph-fantuzzi — APPROVED** [review]
Great work @JakeHappel! The three model functions you created are extremely useful. The endpoints can now use these three functions to access data from the database. The code looks clean and efficient. Also, your loom video does a great job at explaining what was implemented and how it will be used in the future. Overall, good job!

**Review by laurensruiz — APPROVED** [review]
The model looks great! This will make it easier when working on the front end work for the data. Code looks clean and the Loom video did a good job explaining it. Great work!

**Pull request merged**
