### PR TITLE
Bug/fix db link issue

### PR DESCRIPTION
**Pull request by ehsan2793**
it seems that the link to the DB did not work as expected, so I'm updating the PR with the link
just as a recap ==>  
Updated Db. Designer tables and created Admin, Session, Newsfeed tables
the old Db. The designer was missing some of the tables; I used the tables created in code to create this new table design.

new address => Db.Designer

The newsfeed table is not connected to any other table, and the last group did not use it. we can ask the app owner about its use so we can have a better understanding of the app

loom:  https://www.loom.com/share/468a01624c274abe8aa48831c6b12ef0

### CODE REVIEW

**Review by AshleyCoder3 — APPROVED** [review]
Perfect Thank you and the tables look great

**Comment by ehsan2793** [comment]
please let me know if the new link work for you

**Comment by ehsan2793** [comment]
> 

awesome, Ashley thank you

**Review by justinfineberg — APPROVED** [review]
Link works and everything looks great, thanks!

**Review by stevenjhomem — APPROVED** [review]
Great! Thanks Ehsan.

**Pull request merged**
