### PR TITLE
BL-310 Bug/add children

### PR DESCRIPTION
**Pull request by EduarddoEscobar**
## Description

Fixes # (issue where findOrCreateParent was returning different kinds of data)

## Loom Video

Please paste a link here of a quick loom video walking through what you did in your PR .

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by ivanovicu — APPROVED** [review]
Thank you for fixing this!  it helped immensely on my end and the feature I am working on!

**Review by cavazosgeorge — CHANGES_REQUESTED** [review]
Good catch @EduarddoEscobar. Make sure you add a loom video so we can get this approved and merged!

**Comment by kfam22** [comment]
Your changes look good! Great catch to improve performance

**Review by kfam22 — APPROVED** [review]
Your changes look good! Great fix to improve performance

**Review by aamay022 — APPROVED** [review]
Nice fix, looking ready to retrieve the right data

**Review by kylerostler — APPROVED** [review]
Great job fixing this issue by making the functions asynchronous, would have loved to see a quick loom video demonstrating bug, but otherwise a great fix.

**Pull request merged**
