### PR TITLE
Bug/fixing course tests

### PR DESCRIPTION
**Pull request by CamMeiners**
## Description

Fixes # (issue): Changes every instance of "course" to "course-type" or "course-types" in the course testing file. Resolves failing tests. 

## Loom Video

https://www.loom.com/share/2d369beaf20a45d3b5aab5fae6a4d9ea

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by seanmp3 — APPROVED** [review]
Really good work, the tests look strong

**Review by Ryan-E-Mark — APPROVED** [review]
Nice catch on updating the tests to reflect the current db.

**Review by katherineyevsukov — APPROVED** [review]
Changes look good to be merged. Good job updating to make sure tests are passing

**Review by mcmillanj — APPROVED** [review]
changes look good ,just file changes

**Pull request merged**
