### PR TITLE
Feature/role authentication implementation

### PR DESCRIPTION
**Pull request by garrettwyien**
## Description
Pair Programmed : Daniel Reinagel, Garrett Yien (Navigator, Driver)
Went very smoothly and effectively!

Went through API and implemented roleAuthentication middleware where it was applicable (admin, classInstances, courseTypes). roleAuthentication was not implemented in cases where users need personal authorization (e.g. account deletions/updates). 

## Loom Video

https://www.loom.com/share/5399c69272cf44168b4f1cfce1dab402

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by jonahjtr — APPROVED** [review]
looks great

**Review by LeonelHays — APPROVED** [review]
Looks all good to me... although I see some files that are from the model that has been changed, as far as I can see there are no glaring syntax errors.

**Review by RoseGabriely — COMMENTED** [review]
Looks good, please address the merge conflicts so we can get this merged!

**Review by MarkTrepanier — COMMENTED** [review]
The merge conflicts still need fixing, but golden otherwise. I imagine the profile update will soon rid of this?

**Pull request merged**
