### PR TITLE
Eduardo Escobar and I fixed the course id route so you can get one course when you request it

### PR DESCRIPTION
**Pull request by dconley1212**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Loom Video

Please paste a link here of a quick loom video walking through what you did in your PR .

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes
https://www.loom.com/share/5869bd4f74fd4d24856cd3d0408d47de

### CODE REVIEW

**Review by Berenika14 — APPROVED** [review]

**Review by ivanovicu — APPROVED** [review]

**Comment by ivanovicu** [comment]
Good catch ! Gabe's "debugger crash course" really pays off.. especially on backend

**Review by luisbryandr — COMMENTED** [review]
Well this is funny. I was sure I was working from updated main and from where my former team left off at. I was looking to wrap up our work and saw this endpoint wasn't refactored as asked by our ticket on the trello board.  So I re-factored it and included the correct code (...json(req.course)...) the same code / bug fix you all found here.  

Curious how that happened now =), especially since even checking the github repo has the un-refactored code I was working from.

**Review by lizzythomson — APPROVED** [review]
Thanks for fixing this bug! Looks great!

**Review by aamay022 — COMMENTED** [review]
This bug was fixed and is already merged. [PR course/course_id](https://github.com/BloomTech-Labs/coder-heroes-be/pull/92)

**Review by sharontsanchez — APPROVED** [review]
Good work fixing this bug David!

**Pull request merged**
