### PR TITLE
 reorganized data structure for enrollment get by child id

### PR DESCRIPTION
**Pull request by garrettwyien**
## Description

The previous enrollment by child id get returned 1 object per enrollment containing class, enrollment, and child information. This was reorganized such that the request returns a single object per child with an array within that object that contains enrollment and class information for enrolled classes. 

https://trello.com/c/r0IRheDk
https://www.loom.com/share/710580c2a89246c89ff0cef9994682e5

## Type of change

Object reorder

### CODE REVIEW

**Review by LeonelHays — APPROVED** [review]
looks good for implementation, but I do have a question do we need to change the READ-ME?

**Review by DanielReinagel — APPROVED** [review]
This seems like a successful way to get the enrolled classes as objects within the main child object; however, I would recommend using appropriate join methods to have this done automatically instead. The code seems fine this way though, so I'll approve it despite this likely not being best practice.

**Review by paulstgermain — CHANGES_REQUESTED** [review]
This Pull Request still needs a written description of the changes made & why, a Loom recording where you walk us through your work, and a link to the Trello card this PR is related to - please make these changes ASAP, and I'll review this PR then!

**Review by RoseGabriely — COMMENTED** [review]
Looks good thank you. Please address Paul's request so we can get this important change merged in!!

**Comment by RoseGabriely** [comment]
I will be closing this PR as it seems this code exists in another PR, feel free to reopen if necessary!

**Pull request closed without merging**
