### PR TITLE
We created the migration tables for the database schema.

### PR DESCRIPTION
**Pull request by WillisLi**
What we did: Added the tables for the database schema.
Files we changed: We changed the initial profiles table to have an "okta" column.
Why were the files added: We added the files to set up the migrations for seeding default data and fleshing out the endpoints.

Co-authored-by: Amanuel Gilay <emahawey27@gmail.com>
Co-authored-by: Andrew Cummings <andrew.amalee@gmail.com>
[Loom Video](https://www.loom.com/share/f4bbc50b4702439d96b877caa73f4e80)

### CODE REVIEW

**Comment by fernando817mm** [comment]
Nicely done, a lot of work in a short amount of time. Good job!
Not sure what SonarCloud is but it's failing. Maybe something @ashtilawat23 should check out?

**Comment by bradlylewis** [comment]
What is the SonarCloud failing for?

**Comment by WillisLi** [comment]
> What is the SonarCloud failing for?

Says the SONAR_TOKEN env variable isn't set, so I'm thinking we can just set that up in the next meeting with Ash.

**Review by ashtilawat — CHANGES_REQUESTED** [review]
Rebase package-lock on Main into your branch.

**Review by CptHappyHands — APPROVED** [review]
Looks good to me!

**Pull request merged**
