### PR TITLE
Updates seeds to reflect profile removals from previous bug fix

### PR DESCRIPTION
**Pull request by RoseGabriely**
After the most recent merge, there were errors while trying to reseed the database. 
This was because the seeds were still trying to insert profiles 9 & 10 into tables even though they no longer existed. 
Any reference to these deleted profiles was removed from the seeds.

### CODE REVIEW

**Review by MarkTrepanier — COMMENTED** [review]
---

**Review by MarkTrepanier — APPROVED** [review]
Very nice and Fast! I've locally implemented by hand and was able to run seed.

**Review by alextcedwards — APPROVED** [review]
looks good, thanks for doing this.

**Review by CamMeiners — APPROVED** [review]
Looks good to me, every reference of those ID's 9 and 10 looks to be removed.

**Pull request merged**
