### PR TITLE
Bug/newsfeed failing tests

### PR DESCRIPTION
**Pull request by CamMeiners**
## Description

Fixes # (issue): The newsfeed tests weren't passing, fixed typos in naming of files

## Loom Video
https://www.loom.com/share/e0460634f0624f1a81a310ca9cac4eac

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by LeonelHays — APPROVED** [review]
wow, nice code man! When I made the end-points for the newsfeed I tried to do it but I didn't know that the mock needed to just be newsfeed and not [newsfeed].

**Review by Ryan-E-Mark — APPROVED** [review]
Good job finding these little errors!

**Comment by natecheney-dev** [comment]
Great troubleshooting and renaming files to match with the format of the rest of the project.

**Review by mcmillanj — APPROVED** [review]
changes were made, looks goods

**Review by natecheney-dev — APPROVED** [review]
Great troubleshooting and renaming files to match with the format of the rest of the project.

**Review by katherineyevsukov — APPROVED** [review]
Changes look much better.

**Pull request merged**
