### PR TITLE
corrects mismatched okta ids in seeds

### PR DESCRIPTION
**Pull request by paulstgermain**
## Description

This pull request seeks to fix an authentication issue which prevents both users and engineers on this product to access any data in our database through our API's endpoints due to mismatched Okta IDs in our `001_profiles` seed file. This mismatch stems from some work that was done with Okta within the past month that essentially caused each user to receive new ids - this patch assigns those new ids to each of our users except for Test007; this one will come in a later patch.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by alextcedwards — APPROVED** [review]
Paul is the best in the biz. Trust that whatever these are, they are good.

**Review by pjaepole — COMMENTED** [review]
Thank you for the update Paul,
now that we have the right okta_id for our accounts, would we be able to access the backend with any of these accounts(002,003,...) or just the Test001@maildrop.cc?
because before the patch in local environment, with 001 account I was able to get response back from the backend, but not with 002 or 003 account

**Review by pjaepole — APPROVED** [review]

**Comment by ElchinNasirov** [comment]
Thank you for the update!
That will help a lot. Very useful checklist.

**Review by ElchinNasirov — APPROVED** [review]
Thank you for the update!
That will help a lot. Very useful checklist.

**Review by Ryan-E-Mark — APPROVED** [review]
Good catch on the updated Okta_Ids. This should help a lot with synching the front and backend of our application! Thanks Paul

**Comment by paulstgermain** [comment]
> Thank you for the update Paul, now that we have the right okta_id for our accounts, would we be able to access the backend with any of these accounts(002,003,...) or just the [Test001@maildrop.cc](mailto:Test001@maildrop.cc)? because before the patch in local environment, with 001 account I was able to get response back from the backend, but not with 002 or 003 account

You'd be able to access our API/database with any of our test users with this update, except for llama007@maildrop.cc!

**Review by RoseGabriely — COMMENTED** [review]
Could you please explain why you chose to remove profiles with ids 9 and 10?

**Comment by paulstgermain** [comment]
> Could you please explain why you chose to remove profiles with ids 9 and 10?

Sure thing! Those were removed because those test users don't exist in Okta anymore, so there's no need to keep them in our DB. 🙂

**Pull request merged**
