### PR TITLE
added stripe and uuid to dependences for stripe Router

### PR DESCRIPTION
**Pull request by AshleyCoder3**
Added stripe and uuid dependence to backend for use in stripeRouter

### CODE REVIEW

**Review by DanielReinagel — APPROVED** [review]
This seems to add the dependencies properly

**Review by LeonelHays — APPROVED** [review]
yep all good! no other files were changed so we are good.

**Review by pjaepole — APPROVED** [review]
Since I had no idea what these dependencies were I looked it up, 
- The uuid, basically creates unique id for us
>or universally unique identifier, npm package is a secure way to generate cryptographically strong unique identifiers with Node. js that doesn't require a large amount of code.
- stripe, for customer payment
> What is Stripe NPM?
The Stripe Node library provides convenient access to the Stripe API from applications written in server-side JavaScript. For collecting customer and payment information in the browser, use Stripe.
- swagger-jsdoc, swagger-ui-express looks like these are library that helps developer with their endpoints?
>What is swagger in NodeJs?
Swagger is a software tool used for designing, building, documenting, and using RESTful APIs. ... The OpenAPI specification is a specification used for creating interfaces used in describing, producing, consuming, and visualizing RESTful APIs. It is also known as the swagger specification.

**Review by nforman91 — APPROVED** [review]
Just checking, are three imports the only content of this PR? Seems really light for a multiple review/approval process...

**Pull request merged**
