### PR TITLE
adding an availability string to the instructor table

### PR DESCRIPTION
**Pull request by LeonelHays**
## Description

Trello card: https://trello.com/c/QOWBEwn4/130-as-an-instructor-i-can-specify-my-availability-for-teaching-courses

Added a string input field in the instructor table for availability it is null-able and the README will be updated (or it already has if you're in the future)

## Loom Video

https://www.loom.com/share/8103409f958e441cae9b6f7153424f7f

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Ryan-E-Mark — APPROVED** [review]
Great work picking up on this! Seems like a small detail but has obviously been overlooked. I also appreciate you updating the readme with these changes, way to go!

**Review by CamMeiners — APPROVED** [review]

**Review by seanmp3 — APPROVED** [review]
Small but important change, this change will be really useful when teachers start making real classes

**Review by katherineyevsukov — APPROVED** [review]
Looks good to be merged. An availability column on instructors table makes sense.

**Review by mcmillanj — APPROVED** [review]
added availability to instructors table .looks good

**Pull request merged**
